#ifndef XYZ_GENERATOR

#define XYZ_GENERATOR

#include <array>
#include <vector>
#include "../../general/structs/structures.h"

class XyzGenerator {
public: 
  XyzGenerator(std::array<std::array<double, 3>, 3> axisVectors, int numP) : 
    xAxis(axisVectors[0]), 
    yAxis(axisVectors[1]), 
    zAxis(axisVectors[2]),
    numParticles(numP) {};
  
  //Three types of random number gen
  auto randomUniform(unsigned int seed) -> std::vector<std::array<double, 3>>;
  auto uniform() -> std::vector<std::array<double, 3>>;
  auto generateLattice(int numP) -> std::array<int, 3>;

private:
  //TODO: change the names of the axis to be more appropriate considering they are vectors describing the cell
  
  //The vectors describing the 3 axis from which positions should be generated by 
  //describing them as some multiple of each vector in each direction
  std::array<double, 3> xAxis;
  std::array<double, 3> yAxis;
  std::array<double, 3> zAxis;

  int numParticles;
};

#endif

